#!/usr/bin/env bash
# Verification des arguments du terminal

if [$# -lt 4]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assignations

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabbling strict host key checking

scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# verification du transfer
if [ $? -ep 0 ]
then 
	echo "FILE WAS TRANFURED SUCCESSFULLY"
else
	echo "FILE TRANFERT FAILED"
fi
