#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
# Listen on port 80
sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start 
